<?php

namespace Nod4\RpsAdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Exception;
use Nod4\RpsAdminBundle\Entity\History;

/**
 * HistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryRepository extends EntityRepository
{


    public function saveHistory($platform, $browser, $ver)
    {
        $query = "INSERT INTO history (history.platform,history.browser,history.ver,history.view) VALUES ('$platform','$browser','$ver','1')
ON DUPLICATE KEY UPDATE history.view = history.view+1, history.date_update = now() ";
        $em = $this->getEntityManager();
        $stmt = $this->getEntityManager()->getConnection()->prepare($query);
        $stmt->execute();
    }



    public function fetchWithPercents() {

        //select with subselect in this for add sum
        $qb = $this->createQueryBuilder('h')
            ->addSelect('(SELECT SUM(h2.view) FROM Nod4\RpsAdminBundle\Entity\History as h2) as sumView');
        $result = $qb->getQuery()->getResult();
        $newResult = $this->installParamsHistory($result);
        return $newResult;

    }


    private function installParamsHistory(array $history) {
        try {
            $list = array();
            foreach($history as $row){ //tweaking original result
                if($row[0] instanceof History) {
                    $row[0]->setTotalViews($row['sumView']);
                    $list[] = $row[0];
                }
            }
            return $list;
        } catch (Exception $e) {
            throw new Exception("Could not perform copy operation.", 0, $e);
        }
    }

}
