<?php

namespace Nod4\RpsAdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MpContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MpContentRepository extends EntityRepository
{
}
