imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru
    images_directory: '%kernel.root_dir%/../web/uploads/news/images'    
    project: 
        name: 'Райпрофсож'
framework:
    #esi:             ~
    translator:       ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        project: %project%
        images_directory: %images_directory%
    form:
        resources: ['bootstrap_3_layout.html.twig']
      # resources: ['bootstrap_3_horizontal_layout.html.twig']    
        
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
    assets:
        bootstrap_glyphicons_woff:
                    inputs:
                        - %kernel.root_dir%/../web/bundles/rpsadmin/fonts/glyphicons-halflings-regular.woff
                    output: "fonts/glyphicons-halflings-regular.woff"
        
        
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
                  enum: string
        
        
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        
# Swiftmailer Configuration
#swiftmailer:
#    transport: "%mailer_transport%"
#    host:      "%mailer_host%"
#    username:  "%mailer_user%"
#    password:  "%mailer_password%"
#    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Nod4\RpsAdminBundle\Entity\User

#knp_menu:
   #use "twig: false" to disable the Twig extension and the TwigRenderer
 #  twig:
  #    template: KnpMenuBundle::menu.html.twig
   #templating: false
   #default_renderer: twig
    
waldo_datatable:
    all: ~
    js:  
        lengthMenu: [[5,10, 25, 50, -1], [5,10, 25, 50, 'Все']]
        searching: false
    
    